Public Enum Is_System_Named As Byte
    
    'Hex value is: 00000001
    <Description("Name was generated by the system.")>  _
    YES = 1
    
    'Hex value is: 00000000
    <Description("Name was supplied by the user.")>  _
    NO = 0
End Enum
