public enum class Is_System_Named sealed : System::Byte {
    
    // Hex value is: 00000001
    [Description(L"Name was generated by the system.")]
    YES = 1,
    
    // Hex value is: 00000000
    [Description(L"Name was supplied by the user.")]
    NO = 0,
};
